#!/bin/bash
ZVMRUN="$ZEROVM_ROOT/zerovm -QP"
MANIFEST=$(mktemp)
FOUT=$(mktemp)
trap "{ rm -rf $MANIFEST $FOUT; exit $?; }" SIGINT SIGTERM EXIT
if [ -z "$1" ]; then
	echo "USAGE"
	exit 1
fi
EXE="$1"
shift
EXENAME=$(basename "$EXE")
cat > "$MANIFEST" << EOF
Version = 09082012
MemMax = 419430400
NodeName = $EXENAME, 1
Timeout = 50
Nexe = $EXE
EOF
while (( $# )); do
	if [[ "${1:0:1}" == "@" ]]; then
		FPATH="${1:1}"
		FNAME=$(basename "$FPATH")
		FNAME=$(mktemp -u "$FNAME".XXXXXX)
		echo "Channel = $FPATH, $FNAME, 3, 419430400, 419430400, 419430400, 419430400" >> "$MANIFEST"
		ZVMARGS="$ZVMARGS $FNAME"
	else
		ZVMARGS="$ZVMARGS $1"
	fi
	shift
done
cat >> "$MANIFEST" << EOF
Channel = /dev/stdin, /dev/stdin, 0, 419430400, 419430400, 0, 0
Channel = $FOUT, /dev/stdout, 0, 0, 0, 419430400, 419430400
Channel = /dev/stderr, /dev/stderr, 0, 0, 0, 419430400, 419430400
EOF
echo "CommandLine = $ZVMARGS" >> "$MANIFEST"
cat "$MANIFEST" 1>&2
cat - | $ZVMRUN "$MANIFEST" 1>&2
EXT="$?"
#echo -e "\r\n\r\n"
cat $FOUT
exit $EXT

