#Note1: SPECIFY TESTS_ROOT
ifndef MEMMAX
MEMMAX=268435456
endif

#Note2: RELEASE VERSION OF ZEROVM
#Given Makefile - test runner using release build of zerovm

#default types of channels we specifying from make
DEF_CHANTYPE1=0
DEF_CHANTYPE2=0
DEF_CHANTYPE3=1

OUTPUT_LAST=last_test.output
OUTPUT_FAIL=fail_tests.output
TEST_INCLUDES=$(shell find $(TESTS_ROOT) -name "*.h")
TEST_SOURCES=$(shell find $(TESTS_ROOT) -name "*.c")
TEST_OBJECTS=$(addsuffix .o, $(basename $(TEST_SOURCES) ) )
TEST_NVRAMS=$(addsuffix .nvram, $(basename $(TEST_SOURCES) ) )
TEST_MANIFESTS=$(addsuffix .manifest, $(basename $(TEST_SOURCES) ) )
TEST_STDOUTS=$(addsuffix .stdout.std, $(basename $(TEST_SOURCES) ) )
TEST_STDERRS=$(addsuffix .stderr.std, $(basename $(TEST_SOURCES) ) )
TEST_LOG_ZVM=$(addsuffix .zerovm.log, $(basename $(TEST_SOURCES) ) )
TEST_LOG_DEBUG=$(addsuffix .zrtdebug.log, $(basename $(TEST_SOURCES) ) )
TEST_NEXES=$(patsubst %.o, %.nexe, $(TEST_OBJECTS))
TEST_LIST=$(basename $(TEST_SOURCES) )
COUNTER=0

#get pipe from zerovm and parse output
AWK_GET_ERRCODE=awk '{ \
RESULT="FAIL"; \
if (NR == 2) { RETCODE=$$1 } \
if (NR == 5) { \
	if (RETCODE == 0) { RESULT="PASS" } \
	else { RESULT="FAIL" } \
	if ($$0 != "ok") { RESULT="FAIL" } \
print RESULT,"zvmstatus=",$$0 } \
}'

#save failed tests to display it in report
AWK_HANDLE_FAIL=awk '{\
if ( match($$0, "FAIL zvmstatus") != 0 ) {\
	print test, $$0 \
	}\
}' 

TESTBASE=
EXCL=

CFLAGS+=-g #debug
CFLAGS+=-std=gnu99
CFLAGS+=-D_GNU_SOURCE
CFLAGS+=-Wno-long-long -m64
CFLAGS+=-Werror-implicit-function-declaration
CFLAGS+=-I.. -I. 
CFLAGS+=-Iinclude
CFLAGS+=-I$(ZRT_ROOT)/lib

#in order to correectly link glibs substituted functions libzrt should be linked twice
#before object file and after
#For rt tests
LDFLAGS+= -lrt
#For dlopen
LDFLAGS+= -ldl
#math
LDFLAGS+= -lm
#crypt
LDFLAGS+= -lcrypt
#networking mapreduce
LDFLAGS+= -lmapreduce -lnetworking

#uncomment below one if want to display clean files
#VERBOSE_CLEAN=-v

all: clean $(ZEROVM) $(TEST_NEXES) report

resume:$(ZEROVM) $(TEST_NEXES)

clean:
	@find -name "*.scp" | xargs rm -f $(VERBOSE_CLEAN)
	@rm -f $(VERBOSE_CLEAN) $(OUTPUT_LAST)
	@rm -f $(VERBOSE_CLEAN) $(OUTPUT_FAIL)
	@rm -f $(VERBOSE_CLEAN) $(TEST_OBJECTS)
	@rm -f $(VERBOSE_CLEAN) $(TEST_STDOUTS)
	@rm -f $(VERBOSE_CLEAN) $(TEST_STDERRS)
	@rm -f $(VERBOSE_CLEAN) $(TEST_LOG_ZVM)
	@rm -f $(VERBOSE_CLEAN) $(TEST_NEXES)
	@rm -f $(VERBOSE_CLEAN) $(TEST_MANIFESTS)
	@rm -f $(VERBOSE_CLEAN) $(TEST_NVRAMS)
	@rm -f $(VERBOSE_CLEAN) $(TEST_LOG_DEBUG)

$(ZEROVM):
	$(error "$(ZEROVM) does not exist")

$(TEST_NEXES): $(TEST_SOURCES) $(TEST_INCLUDES)
#increase test counter
	$(eval COUNTER:=$(shell echo $$(($(COUNTER)+1))) )
#prrepare variables
	$(eval BASENAME:=$(basename $@))
	$(eval NAMEONLY:=$(notdir $(BASENAME)))
	$(eval SPECIFIC_TEST_FLAGS:=$(CFLAGS-$(NAMEONLY).c))
	$(eval SPECIFIC_TEST_CMDLINE:=$(CMDLINE-$(NAMEONLY).c))
	$(eval SPECIFIC_TEST_ENV:=$(ENV-$(NAMEONLY).c))
	$(eval SPECIFIC_TEST_MAPPING:=$(MAPPING-$(NAMEONLY).c))
#channels testing suport
	$(eval SPECIFIC_TEST_CHANTYPE1:=$(firstword $(CHANTYPE1-$(NAMEONLY).c) $(DEF_CHANTYPE1)))
	$(eval SPECIFIC_TEST_CHANTYPE2:=$(firstword $(CHANTYPE2-$(NAMEONLY).c) $(DEF_CHANTYPE2)))
	$(eval SPECIFIC_TEST_CHANTYPE3:=$(firstword $(CHANTYPE3-$(NAMEONLY).c) $(DEF_CHANTYPE3)))
	@echo "TEST RUN $@ "
#compile
	@$(CC) -c -o $(BASENAME).o $(CFLAGS) $(SPECIFIC_TEST_FLAGS) $(BASENAME).c
	@$(CC) -o $@ $(BASENAME).o $(LDFLAGS)
#prepare scripts for debug purposes with GDB
	@sed s@{NEXE_FULL_PATH}@$(CURDIR)/$(BASENAME).nexe@g $(ZRT_ROOT)/gdb_commands.template > $(CURDIR)/$(BASENAME).scp
#prepare manifest
	@sed s@{OUTFILE}@$(CURDIR)/$(BASENAME)@g manifest_tests.template | \
	 sed s@{ABS_PATH}@$(CURDIR)/@g | \
	 sed s@{CHANTYPE1}@$(SPECIFIC_TEST_CHANTYPE1)@g | \
	 sed s@{CHANTYPE2}@$(SPECIFIC_TEST_CHANTYPE2)@g | \
	 sed s@{CHANTYPE3}@$(SPECIFIC_TEST_CHANTYPE3)@g | \
	 sed s@{MOUNTS_PATH}@$(ZRT_ROOT)/mounts/@g | \
	 sed s@{MEMMAX}@$(MEMMAX)@g > $(CURDIR)/$(BASENAME).manifest
#prepare nvram
	@sed s@{ENVIRONMENT}@"$(SPECIFIC_TEST_ENV)"@g nvram_tests.template | \
	 sed s@{MAPPING}@"$(SPECIFIC_TEST_MAPPING)"@g | \
	 sed s@{BR}@'\n'@g | \
	 sed s@{COMMAND_LINE}@"$(SPECIFIC_TEST_CMDLINE)"@g > $(CURDIR)/$(BASENAME).nvram
#Run test under zerovm and display returned error code
#$shell should could not be used to get test result from file because it unexpectadly
#using contents of previosly saved test output, and it is the main reason why using awk;
#parsing correct output retrieved via pipe
#Note that zerovm option -l6 is used because working with big file
	@$(ZEROVM) -M$(CURDIR)/$(BASENAME).manifest -l6 \
	| $(AWK_GET_ERRCODE) \
	| $(AWK_HANDLE_FAIL) test="$@"  2>&1 | tee -a $(OUTPUT_FAIL)

report: $(OUTPUT_FAIL)
#display tests resuts
	@echo --------------------------------------------
	@echo $(COUNTER) tests was executed
	@echo -n "Failed "
	@echo -n `cat $(OUTPUT_FAIL) | wc -l`
	@echo " tests:"
	@cat $(OUTPUT_FAIL)
	@rm -f $(OUTPUT_FAIL) $(OUTPUT_LAST)

$(OUTPUT_FAIL):
#has no output fail if this rule is active
	$(error Nothing output)
