make $@

x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/animate utilities/animate.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/compare utilities/compare.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/composite utilities/composite.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/conjure utilities/conjure.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/convert utilities/convert.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/display utilities/display.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/identify utilities/identify.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/import utilities/import.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/mogrify utilities/mogrify.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/montage utilities/montage.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm
x86_64-nacl-gcc -static -std=gnu99 -I/home/kit/git/zrt/include -I/home/kit/git/zrt/include/libxml2 -Wall -m64 -Wl,-T/home/kit/zvm-sdk/x86_64-nacl/lib64/ldscripts/elf64_nacl.x.static -Wl,/home/kit/git/zrt/lib/zrt.o -Wl,-L/home/kit/git/zrt/lib -Wl,-lzrt -Wl,-lfs -Wl,-lstdc++ -o utilities/stream utilities/stream.o magick/.libs/libMagickCore.a wand/.libs/libMagickWand.a /home/kit/git/zrt/libports/imagemagick-6.6.9.7/magick/.libs/libMagickCore.a -llcms2 -ltiff -ljasper -ljpeg -lpng -lz -lm

