.\"Shiju P. Nair September 30, 2004
.TH TIFFDIFF 1 "March 25, 2006"
.SH NAME 
tiffdiff - Little cms TIFF compare utility.
.SH SYNOPSIS
.B tiffdiff
.RI [ flags ] " input.tif output.tif"
.SH DESCRIPTION
lcms is a standalone CMM engine, which deals with the color management.
It implements a fast transformation between ICC profiles.
.B tiffdiff
is Little cms TIFF compare utility.
.SH OPTIONS
.TP
.B \-o<tiff>
Output TIFF file.
.TP
.B \-g<CGATS>
Output results in CGATS file.
.TP
.B \-v
Verbose (show warnings).
.TP
.B \-h
Help.
.fi				
.SH NOTES
For suggestions, comments, bug reports etc. send mail to
info@littlecms.com.
.SH SEE ALSO
.BR jpegicc (1),
.BR tifficc (1),
.BR icc2ps (1),
.BR icclink (1),
.BR icctrans (1),
.BR wtpt (1)
.SH AUTHOR
This manual page was written by Shiju p. Nair <shiju.p@gmail.com>,
for the Debian project.
