/* pth_acdef.h.  Generated by configure.  */
/* pth_acdef.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `dlclose' function. */
#define HAVE_DLCLOSE 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `dlopen' function. */
#define HAVE_DLOPEN 1

/* Define to 1 if you have the `dlsym' function. */
#define HAVE_DLSYM 1

/* Define to 1 if you have the <dmalloc.h> header file. */
/* #undef HAVE_DMALLOC_H */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <ex.h> header file. */
/* #undef HAVE_EX_H */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `getcontext' function. */
#define HAVE_GETCONTEXT 1

/* Define to 1 if you have the `gettimeofday' function. */
#define HAVE_GETTIMEOFDAY 1

/* define if gettimeofday(2) wants a single-argument only */
/* #undef HAVE_GETTIMEOFDAY_ARGS1 */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `dmalloc' library (-ldmalloc). */
/* #undef HAVE_LIBDMALLOC */

/* Define to 1 if you have the `ex' library (-lex). */
/* #undef HAVE_LIBEX */

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `sfio' library (-lsfio). */
/* #undef HAVE_LIBSFIO */

/* Define to 1 if you have the `socket' library (-lsocket). */
/* #undef HAVE_LIBSOCKET */

/* define if "long double" type exists */
#define HAVE_LONGDOUBLE 1

/* Define to 1 if you have the `longjmp' function. */
#define HAVE_LONGJMP 1

/* define if "long long" type exists */
#define HAVE_LONGLONG 1

/* Define to 1 if you have the `makecontext' function. */
#define HAVE_MAKECONTEXT 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <net/errno.h> header file. */
/* #undef HAVE_NET_ERRNO_H */

/* define if typedef nfds_t exists in header poll.h */
#define HAVE_NFDS_T 1

/* define if typedef off_t exists in header sys/types.h */
#define HAVE_OFF_T 1

/* Define to 1 if you have the <paths.h> header file. */
#define HAVE_PATHS_H 1

/* define if typedef pid_t exists in header sys/types.h */
#define HAVE_PID_T 1

/* Define to 1 if you have the `poll' function. */
#define HAVE_POLL 1

/* define if pre-processor define POLLIN exists in header poll.h */
#define HAVE_POLLIN 1

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define to 1 if you have the `readv' function. */
#define HAVE_READV 1

/* define if pre-processor define RTLD_NEXT exists in header dlfcn.h */
/* #undef HAVE_RTLD_NEXT */

/* Define to 1 if you have the `select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the `setcontext' function. */
#define HAVE_SETCONTEXT 1

/* Define to 1 if you have the `setjmp' function. */
#define HAVE_SETJMP 1

/* Define to 1 if you have the <setjmp.h> header file. */
#define HAVE_SETJMP_H 1

/* Define to 1 if you have the <sfio.h> header file. */
/* #undef HAVE_SFIO_H */

/* Define to 1 if you have the `sigaction' function. */
/* #undef HAVE_SIGACTION */

/* Define to 1 if you have the `sigaltstack' function. */
#define HAVE_SIGALTSTACK 1

/* Define to 1 if you have the `siglongjmp' function. */
#define HAVE_SIGLONGJMP 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `sigpending' function. */
#define HAVE_SIGPENDING 1

/* Define to 1 if you have the `sigprocmask' function. */
#define HAVE_SIGPROCMASK 1

/* Define to 1 if you have the `sigsetjmp' function. */
/* #undef HAVE_SIGSETJMP */

/* Define to 1 if you have the `sigstack' function. */
#define HAVE_SIGSTACK 1

/* Define to 1 if you have the `sigsuspend' function. */
#define HAVE_SIGSUSPEND 1

/* define if typedef sig_atomic_t exists in header signal.h */
#define HAVE_SIG_ATOMIC_T 1

/* define if typedef size_t exists in header stdlib.h */
#define HAVE_SIZE_T 1

/* define if typedef socklen_t exists in header sys/socket.h */
#define HAVE_SOCKLEN_T 1

/* define if typedef ssize_t exists in header sys/types.h */
#define HAVE_SSIZE_T 1

/* define if attribute ss_base exists in struct sigaltstack from header
   sys/signal.h */
/* #undef HAVE_SS_BASE */

/* define if attribute ss_sp exists in struct sigaltstack from header
   sys/signal.h */
#define HAVE_SS_SP 1

/* define if typedef stack_t exists in header signal.h */
#define HAVE_STACK_T 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* define if exists "struct timespec" */
#define HAVE_STRUCT_TIMESPEC 1

/* Define to 1 if you have the `swapcontext' function. */
#define HAVE_SWAPCONTEXT 1

/* Define to 1 if you have the `syscall' function. */
/* #undef HAVE_SYSCALL */

/* define if pre-processor define SYS_read exists in header sys/syscall.h */
#define HAVE_SYS_READ 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socketcall.h> header file. */
/* #undef HAVE_SYS_SOCKETCALL_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/syscall.h> header file. */
#define HAVE_SYS_SYSCALL_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
#define HAVE_SYS_UIO_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `usleep' function. */
#define HAVE_USLEEP 1

/* Define to 1 if you have the `writev' function. */
#define HAVE_WRITEV 1

/* Define to 1 if you have the `_longjmp' function. */
#define HAVE__LONGJMP 1

/* Define to 1 if you have the `_setjmp' function. */
#define HAVE__SETJMP 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* define to enable Pth debugging */
/* #undef PTH_DEBUG */

/* define if using Dmalloc in GNU pth */
/* #undef PTH_DMALLOC */

/* define if using OSSP ex in GNU pth */
/* #undef PTH_EX */

/* define for machine context dispatching */
#define PTH_MCTX_DSP_use PTH_MCTX_DSP_sc

/* define for machine context method */
#define PTH_MCTX_MTH_use PTH_MCTX_MTH_mcsc

/* define for machine context stack */
#define PTH_MCTX_STK_use PTH_MCTX_STK_mc

/* define for number of signals */
#define PTH_NSIG 32

/* define for stack growth */
#define PTH_STACKGROWTH -1

/* define for the paths to syscall dynamic libraries */
#define PTH_SYSCALL_LIBS ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1
