/* Automatically generated by po-to-tbl from tar.po.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"exec/tcp: Service not available", 2},
  {"Try `%s --help' for more information.\n", 3},
  {"Skipping to next header", 4},
  {"Size", 5},
  {"Cannot seek to %ld in file %s", 6},
  {"You must use a compression option (--gzip, --compress\n\
or --use-compress-program) with --block-compress", 7},
  {"VERIFY FAILURE: %d invalid header(s) detected", 8},
  {"Blocksize = %d records", 9},
  {"%s: Deleting %s\n", 10},
  {"  -N, --newer=DATE           only store files newer than DATE\n\
      --after-date=DATE      same as -N\n", 11},
  {"Read checkpoint %d", 12},
  {"\n\
On *this* particular tar, the defaults are -f %s and -b %d.\n", 13},
  {"Cannot symlink %s to %s", 14},
  {"Unknown demangling command %s", 15},
  {"At beginning of tape, quitting now", 16},
  {"Symlinked %s to %s", 17},
  {"%s: Cannot link to %s, copying instead", 18},
  {"\n\
Archive format selection:\n\
  -V, --label=NAME                   create archive with volume name NAME\n\
  -o, --old-archive, --portability   write a V7 format archive (not ANSI)\n\
  -z, --gzip, --ungzip               filter the archive through gzip\n\
  -Z, --compress, --uncompress       filter the archive through compress\n\
      --use-compress-program=PROG    filter through PROG (must accept -d)\n", 19},
  {"Options [0-7][lmh] not supported by *this* tar", 20},
  {"Cannot fork", 21},
  {"EOF?  What does that mean?", 22},
  {"Mandatory arguments to long options are mandatory for short options too.\n\
\n\
      --help            display this help and exit\n\
      --version         output version information and exit\n", 23},
  {"Cannot open %s", 24},
  {"Mandatory or optional arguments to long options are mandatory or optional\n\
for short options too.\n", 25},
  {"This does not look like a tar archive", 26},
  {"Read error at byte %ld, reading %d bytes, in file %s", 27},
  {"Cannot use multi-volume compressed archives", 28},
  {"File name %s%s too long", 29},
  {"Volume mismatch!  %s!=%s", 30},
  {"Cannot use compressed or remote archives", 31},
  {"%s: Data differs\n", 32},
  {"\n\
Device selection and switching:\n\
  -f, --file=[HOSTNAME:]FILE     use archive file or device FILE on HOSTNAME\n\
      --force-local              archive file is local even if has a colon\n\
      --rsh-command=COMMAND      use remote COMMAND instead of rsh\n\
  -[0-7][lmh]                    specify drive and density\n\
  -M, --multi-volume             create/list/extract multi-volume archive\n\
  -L, --tape-length=NUM          change tape after writing NUM x 1024 bytes\n\
  -F, --info-script=FILE         run script at end of each tape (implies -M)\n\
      --new-volume-script=FILE   same as -F FILE\n", 33},
  {"No archive name given, what should I do?", 34},
  {" n [name]   Give a new filename for the next (and subsequent) volume(s)\n\
 q          Abort tar\n\
 !          Spawn a subshell\n\
 ?          Print this list\n", 35},
  {"\n\
Device blocking:\n\
  -b, --block-size=BLOCKS    block size of BLOCKS x 512 bytes\n\
      --block-compress       block the output of compression for tapes\n\
  -i, --ignore-zeros         ignore blocks of zeros in archive (means EOF)\n\
  -B, --read-full-blocks     reblock as we read (for reading 4.2BSD pipes)\n", 36},
  {"Could not change access and modification times of %s", 37},
  {"Could not create directory %s", 38},
  {"--Continued at byte %ld--\n", 39},
  {"Cannot fork!", 40},
  {"Garbage command", 41},
  {"Only one compression option permitted", 42},
  {"Total bytes written: %d\n", 43},
  {"Cannot read %s", 44},
  {"Cannot open a pipe", 45},
  {"\n\
Main operation mode:\n\
  -t, --list              list the contents of an archive\n\
  -x, --extract, --get    extract files from an archive\n\
  -c, --create            create a new archive\n\
  -d, --diff, --compare   find differences between archive and file system\n\
  -r, --append            append files to the end of an archive\n\
  -u, --update            only append files newer than copy in archive\n\
  -A, --catenate          append tar files to an archive\n\
      --concatenate       same as -A\n\
      --delete            delete from the archive (not on mag tapes!)\n", 46},
  {"%s: Unknown file type; file ignored", 47},
  {"Cannot read link %s", 48},
  {"Archive %s EOF not on block boundary", 49},
  {"Visible long name error", 50},
  {"Cannot extract `%s' -- file is continued from another volume", 51},
  {"Bad regular expression: %s", 52},
  {"Cannot execute remote shell", 53},
  {"%s: Does not exist\n", 54},
  {"Invalid date format `%s'", 55},
  {"Too many errors, quitting", 56},
  {"Cannot exec %s", 57},
  {"Invalid value for blocksize", 58},
  {"Creating directory:", 59},
  {"Read error on %s", 60},
  {"Cannot open archive %s", 61},
  {"Cannot add file %s", 62},
  {"Cannot change owner of %s to uid %d gid %d", 63},
  {"Cannot keep old files on this system", 64},
  {"Child returned status %d", 65},
  {"Added write and execute permission to directory %s", 66},
  {"Missing filename after -C", 67},
  {"\n\
Local file selection:\n\
  -C, --directory DIR        change to directory DIR\n\
  -T, --files-from=NAME      get names to extract or create from file NAME\n\
      --null                 -T reads null-terminated names, disable -C\n\
      --exclude=FILE         exclude file FILE\n\
  -X, --exclude-from=FILE    exclude files listed in FILE\n\
  -P, --absolute-paths       don't strip leading `/'s from file names\n\
  -h, --dereference          dump instead the files symlinks point to\n\
  -l, --one-file-system      stay in local file system when creating archive\n\
  -K, --starting-file=NAME   begin at file NAME in the archive\n", 68},
  {"Wrote %ld of %ld bytes to file %s", 69},
  {"Could not make %s", 70},
  {"%s: is unchanged; not dumped", 71},
  {"\n\
Informative output:\n\
      --help            print this help, then exit\n\
      --version         print tar program version number, then exit\n\
  -v, --verbose         verbosely list files processed\n\
      --checkpoint      print directory names while reading the archive\n\
      --totals          print total bytes written while creating archive\n\
  -R, --record-number   show record number within archive with each message\n\
  -w, --interactive     ask for confirmation for every action\n\
      --confirmation    same as -w\n", 72},
  {"Write checkpoint %d", 73},
  {"Could not backspace archive file; it may be unreadable without -i", 74},
  {"Removing drive spec from names in the archive", 75},
  {"Verify ", 76},
  {"File %s shrunk by %d bytes, padding with zeros", 77},
  {"Cannot change directory to %d", 78},
  {"Cannot remove %s", 79},
  {"Cannot chown file %s to uid %d gid %d", 80},
  {"Could not link %s to %s", 81},
  {"(child) Pipe to stdin", 82},
  {"%s: Mode or device-type changed\n", 83},
  {"\n\
Operation mode modificators:\n\
  -W, --verify               attempt to verify the archive after writing it\n\
      --remove-files         remove files after adding them to the archive\n\
  -k, --keep-old-files       don't overwrite existing files from archive\n\
  -S, --sparse               handle sparse files efficiently\n\
  -O, --to-stdout            extract files to standard output\n\
  -G, --incremental          handle old GNU-format incremental backup\n\
  -g, --listed-incremental   handle new GNU-format incremental backup\n\
      --ignore-failed-read   do not exit with non-zero on unreadable files\n", 84},
  {"Cannot exec a shell %s", 85},
  {"rmtd: Premature eof\n", 86},
  {"%d at %d\n", 87},
  {"Amount actually written is (I hope) %d.\n", 88},
  {"Cannot write to compression program", 89},
  {"Cannot change to directory %s", 90},
  {"Directory %s has been renamed", 91},
  {"Could only write %d of %d bytes to file %s", 92},
  {" unknown file type `%c'\n", 93},
  {"Cannot close a file #%d", 94},
  {"Directory %s is new", 95},
  {"tar (child)", 96},
  {"Could not rewind archive file for verify", 97},
  {"\n\
Usage: %s [OPTION]...\n", 98},
  {"Child died with signal %d%s", 99},
  {"%s: Device numbers changed\n", 100},
  {"Reading %s\n", 101},
  {"Mod time", 102},
  {"Could not create symlink to %s", 103},
  {"Child cannot fork", 104},
  {"Unknown file type '%c' for %s, extracted as normal file", 105},
  {"Cannot verify multi-volume archives", 106},
  {"Multiple archive files requires --multi-volume", 107},
  {"Could not allocate memory for diff buffer of %d bytes", 108},
  {"WARNING: Archive is incomplete", 109},
  {"Cannot rename %s to %s", 110},
  {" (core dumped)", 111},
  {"%s: On a different filesystem; not dumped", 112},
  {"rmtd: Garbage command %c\n", 113},
  {"Unexpected EOF in archive", 114},
  {"--Mangled file names--\n", 115},
  {"%s is not continued on this volume", 116},
  {"This volume is out of sequence", 117},
  {"%s: Symlink differs\n", 118},
  {"[child] Pipe to stdout", 119},
  {"rmtd: Cannot allocate buffer space\n", 120},
  {"Hmm, this doesn't look like a tar archive", 121},
  {"Cannot write to %s", 122},
  {"Could not get current directory: %s", 123},
  {"Cannot read from compression program", 124},
  {"You may not specify more than one of the r, c, t, x, or d options", 125},
  {"Skipping to next file header", 126},
  {"\007Prepare volume #%d for %s and hit return: ", 127},
  {"Only wrote %ld of %ld bytes to file %s", 128},
  {"Only read %d bytes from archive %s", 129},
  {"Missing file name after -C", 130},
  {"Cannot change mode of file %s to %lo", 131},
  {"Cannot stat %s", 132},
  {"(child) Pipe to stdout", 133},
  {"%s is the wrong size (%ld != %ld + %ld)", 134},
  {"No new volume; exiting.\n", 135},
  {"%s is the archive; not dumped", 136},
  {"Cannot verify stdin/stdout archive", 137},
  {"Removing leading / from absolute links", 138},
  {"Error while deleting %s", 139},
  {"Unknown file type '%c' for %s, diffed as normal file", 140},
  {"--Volume Header--\n", 141},
  {"Cannot open directory %s", 142},
  {"Could not write to file %s", 143},
  {"%s: No longer a directory\n", 144},
  {"rec %10ld: ", 145},
  {"Archive not labelled to match %s", 146},
  {"Archive to stdin", 147},
  {"Premature end of file", 148},
  {"%s: Not a regular file\n", 149},
  {"EOF in archive file", 150},
  {"%s: %s differs\n", 151},
  {"%s: Not found in archive", 152},
  {"Cannot allocate buffer space", 153},
  {"Cannot open file %s", 154},
  {"((child)) Pipe to stdin", 155},
  {"Uid", 156},
  {"You must specify one of the r, c, t, x, or d options", 157},
  {"Gid", 158},
  {"Unexpected EOF in mangled names", 159},
  {"Usage: %s [OPTION]... [FILE]...\n", 160},
  {"Could not allocate memory for blocking factor %d", 161},
  {"Cannot read confirmation from user", 162},
  {"%s: Could only read %d of %ld bytes\n", 163},
  {"Omitting %s", 164},
  {"((child)) Pipe to stdout", 165},
  {"%s: Not linked to %s\n", 166},
  {"Cannot close descriptor %d", 167},
  {"Mode", 168},
  {"Renamed %s to %s", 169},
  {"Cannot dup %s", 170},
  {"WARNING: Cannot close %s (%d, %d)", 171},
  {"Cannot chdir to %s", 172},
  {"%s: No such file or directory\n", 173},
  {"Write to compression program short %d bytes", 174},
  {"Could not get current directory", 175},
  {"Error while closing %s", 176},
  {" link to %s\n", 177},
  {"Unexpected EOF on archive file", 178},
  {"[child] Pipe to stdin", 179},
  {"Cannot stat file %s", 180},
  {"Cannot allocate %d bytes for restore", 181},
  {"Archive to stdout", 182},
  {"\n\
Handling of file attributes:\n\
      --atime-preserve         don't change access times on dumped files\n\
  -m, --modification-time      don't extract file modified time\n\
      --same-owner             create extracted files with the same ownership \n\
  -p, --same-permissions       extract all protection information\n\
      --preserve-permissions   same as -p\n\
  -s, --same-order             sort names to extract to match archive\n\
      --preserve-order         same as -s\n\
      --preserve               same as both -p and -s\n", 183},
  {"Could not create file %s", 184},
  {"Cannot update or verify compressed archives", 185},
  {"Only wrote %u of %u bytes to %s", 186},
  {"WARNING: No volume header", 187},
  {"Too many args with -T option", 188},
  {"Visible longname error", 189},
  {"Removing leading / from absolute path names in the archive", 190},
  {"Obsolete option name replaced by --absolute-names", 191},
  {"File %s\n", 192},
  {"Read error at byte %ld reading %d bytes in file %s", 193},
  {"%s: File shrunk by %d bytes, (yark!)", 194},
  {"Junk files\n", 195},
  {"file %s\n", 196},
  {"Skip %ld\n", 197},
  {"Out of first loop\n", 198},
  {"Saved %d recs, need %d more\n", 199},
  {"New block\n", 200},
  {"Header type %d\n", 201},
  {"Deleting non-header from archive", 202},
  {"File %s ", 203},
  {"Flush it\n", 204},
  {"Flushing %d recs from %s\n", 205},
  {"Block: %d <= %d  ", 206},
  {"Block %d left\n", 207},
  {"Final %d\n", 208},
  {"Need %d kept_in %d keep %d\n", 209},
  {"Flush...\n", 210},
  {"Copying %d\n", 211},
  {"Now new %d  need %d  keep %d  keep_in %d rec %d/%d\n", 212},
  {"Write block\n", 213},
  {"Fore to %x\n", 214},
  {"Could not re-position archive file", 215},
};

int _msg_tbl_length = 215;
