#ifndef __NVRAM_H__
#define __NVRAM_H__

#define NVRAM_MAX_FILE_SIZE 10240
#define NVRAM_MAX_SECTION_NAME_LEN 20
#define NVRAM_MAX_SECTIONS_COUNT 5
#define NVRAM_MAX_OBSERVERS_COUNT NVRAM_MAX_SECTIONS_COUNT
#define NVRAM_MAX_RECORDS_IN_SECTION 10
#define NVRAM_MAX_KEYS_COUNT_IN_RECORD 4
#define NVRAM_MAX_KEY_LENGTH 20

#endif //__NVRAM_H__
