.TH libpng12-config 1 "15 Jan 2003" "libpng" "Debian GNU/Linux"
.SH NAME
libpng12-config \- get information about installed libpng library
.SH SYNOPSIS
.B libpng12-config
[\fIOPTION\fR] ...
.SH DESCRIPTION
Provides information about libpng library.

Known values for OPTION are:
.TP
\fB\-\-prefix\fR
print libpng prefix
.TP
\fB\-\-libdir\fR
print path to directory containing library
.TP
\fB\-\-libs\fR
print library linking information
.TP
\fB\-\-ccopts\fR
print compiler options
.TP
\fB\-\-cppflags\fR
print pre-processor flags
.TP
\fB\-\-cflags\fR
print preprocessor flags, I_opts, and compiler options
.TP
\fB\-\-I_opts\fR
print "-I" include options
.TP
\fB\-\-L_opts\fR
print linker "-L" flags for dynamic linking
.TP
\fB\-\-R_opts\fR
print dynamic linker "-R" or "-rpath" flags
.TP
\fB\-\-ldopts\fR
print linker options
.TP
\fB\-\-ldflags\fR
print linker flags (ldopts, L_opts, R_opts, and libs)
.TP
\fB\-\-static\fR
revise subsequent outputs for static linking
.TP
\fB\-\-help\fR
print this help and exit
.TP
\fB\-\-version\fR
print version information
.SH "AUTHOR"
This manpage has been written by Junichi Uekawa <dancer@debian.org>
for Debian GNU/Linux system, with the help of help2man, and
may be used by others.


